= Table.AddColumn(#"Changed Type", "CampaignRemoved", each if [Campaign] = "FireWire>Cables" then true
else if [Campaign] = "USB>Floppy Drive" then true
else if [Campaign] = "USB to Serial Adapter" then true
else if [Campaign] = "Firewire PCI Card" then true
else if [Campaign] = "FireWire>Hubs" then true
else if [Campaign] = "USB>Extension Cables" then true
else if [Campaign] = "Campaign #37" then true
else if [Campaign] = "PC Remote Control" then true
else if [Campaign] = "Docking Stations - Spanish" then true
else if [Campaign] = "Video Splitter" then true
else if [Campaign] = "USB to Serial Adapter - Scandinavia" then true
else if [Campaign] = "Other Products IV" then true
else if [Campaign] = "Retractable Cables" then true
else if [Campaign] = "Nate Kartchner" then true
else if [Campaign] = "Lewis Gunter" then true
else if [Campaign] = "Audio>Pro Audio" then true
else if [Campaign] = "KVM" then true
else if [Campaign] = "Serial>USB to Serial Adapter" then true
else if [Campaign] = "Video>Switches" then true
else if [Campaign] = "GPS" then true
else if [Campaign] = "Audio>Adapters" then true
else if [Campaign] = "Displays" then true
else if [Campaign] = "Networking>Wireless" then true
else if [Campaign] = "Accessories" then true
else if [Campaign] = "Video>IP Cameras" then true
else if [Campaign] = "Mice & Keyboards" then true
else if [Campaign] = "Eco-Friendly" then true
else if [Campaign] = "June 2008 Optimized Products - Jimmy" then true
else if [Campaign] = "API Part Numbers 7500-9000" then true
else if [Campaign] = "Wireless HDMI - Search" then true
else if [Campaign] = "Yochi Shoes" then true
else if [Campaign] = "Yochi Yochis" then true
else if [Campaign] = "Recently Added on Site 10/7/11" then true
else if [Campaign] = "Cisco Parts" then true
else if [Campaign] = "MOS Products" then true
else if [Campaign] = "USB to Parallel Adapter" then true
else if [Campaign] = "Wireless Cardbus" then true
else if [Campaign] = "USB to PS/2 Adapter" then true
else if [Campaign] = "2.5"" Hard Drive Enclosure" then true
else if [Campaign] = "Campaign #26" then true
else if [Campaign] = "Fastlynx" then true
else if [Campaign] = "Campaign #29" then true
else if [Campaign] = "USB>Hubs" then true
else if [Campaign] = "USB to Parallel Adapter - Canada" then true
else if [Campaign] = "USB to Parallel Adapter - Japan" then true
else if [Campaign] = "USB to Parallel Adapter - Chinese Countries" then true
else if [Campaign] = "Docking Stations - Korean" then true
else if [Campaign] = "Docking Stations - German" then true
else if [Campaign] = "USB>Share Switch" then true
else if [Campaign] = "USB to Serial Adapter - Europe (other)" then true
else if [Campaign] = "HDMI>Cables" then true
else if [Campaign] = "Other Products II" then true
else if [Campaign] = "Content Match" then true
else if [Campaign] = "Sam Garfield" then true
else if [Campaign] = "Audio" then true
else if [Campaign] = "DVI>Converters" then true
else if [Campaign] = "DVI>Misc" then true
else if [Campaign] = "Hard Drive>Accessories" then true
else if [Campaign] = "HDMI>Switches" then true
else if [Campaign] = "Other" then true
else if [Campaign] = "PCI/PCMCIA Card" then true
else if [Campaign] = "DVI>General" then true
else if [Campaign] = "Audio>Speakers-Microphones-Headphones" then true
else if [Campaign] = "Brand Names" then true
else if [Campaign] = "Video>Calibration" then true
else if [Campaign] = "Networking>Gateways" then true
else if [Campaign] = "Worst Offenders" then true
else if [Campaign] = "Gefen Part Numbers" then true
else if [Campaign] = "Gefen Products" then true
else if [Campaign] = "Speaker Accessories" then true
else if [Campaign] = "Jon" then true
else if [Campaign] = "ikiki IGG" then true
else if [Campaign] = "3D Printer" then true
else if [Campaign] = "Campaign #4" then true
else if [Campaign] = "USB to IrDA Adapter" then true
else if [Campaign] = "USB to Bluetooth" then true
else if [Campaign] = "USB to IDE Adapter - OLD" then true
else if [Campaign] = "Hard Drive>Cases" then true
else if [Campaign] = "Campaign #27" then true
else if [Campaign] = "Other Adapters/Converters" then true
else if [Campaign] = "USB>Cards" then true
else if [Campaign] = "C++ Source Code Modules" then true
else if [Campaign] = "USB to Parallel Adapter - Europe (other)" then true
else if [Campaign] = "Docking Stations - Japanese" then true
else if [Campaign] = "USB to Serial Adapter - Brazil" then true
else if [Campaign] = "USB to Serial Adapter - other English speaking" then true
else if [Campaign] = "Input Devices" then true
else if [Campaign] = "Other Products III" then true
else if [Campaign] = "Eyner Ramirez" then true
else if [Campaign] = "Dan Garfield" then true
else if [Campaign] = "Gaming Opt" then true
else if [Campaign] = "HDMI>Misc" then true
else if [Campaign] = "IR" then true
else if [Campaign] = "Notebook Accessories" then true
else if [Campaign] = "Parallel" then true
else if [Campaign] = "Video>Extenders" then true
else if [Campaign] = "Video>Splitters" then true
else if [Campaign] = "Networking>Cables" then true
else if [Campaign] = "VoIP" then true
else if [Campaign] = "Video>Cable Testers" then true
else if [Campaign] = "Optimus Mini Three" then true
else if [Campaign] = "API Part Numbers 10500-12000" then true
else if [Campaign] = "TV Converter Box" then true
else if [Campaign] = "Content Network Campaign" then true
else if [Campaign] = "Product Listings" then true
else if [Campaign] = "Halite" then true
else if [Campaign] = "Local" then true
else if [Campaign] = "How To" then true
else if [Campaign] = "Home Theater Opt" then true
else if [Campaign] = "Scoovy Bumpers" then true
else if [Campaign] = "Campaign #6" then true
else if [Campaign] = "Docking Stations" then true
else if [Campaign] = "KVM Switches" then true
else if [Campaign] = "USB 2.0 IDE Adapter" then true
else if [Campaign] = "Campaign #42" then true
else if [Campaign] = "Campaign #43" then true
else if [Campaign] = "USB to Parallel Adapter - Brazil" then true
else if [Campaign] = "USB to Serial Adapter - Germany" then true
else if [Campaign] = "USB to Serial Adapter - France" then true
else if [Campaign] = "USB/FireWire Combo Card" then true
else if [Campaign] = "USB to Serial Adapter - Australia / NZ" then true
else if [Campaign] = "Serial Device Servers" then true
else if [Campaign] = "Connectivity" then true
else if [Campaign] = "Europe" then true
else if [Campaign] = "Gefen" then true
else if [Campaign] = "Other Products V" then true
else if [Campaign] = "601" then true
else if [Campaign] = "Jon Sanderson" then true
else if [Campaign] = "Networking>Cellular" then true
else if [Campaign] = "PC Accessories" then true
else if [Campaign] = "Video>VGA" then true
else if [Campaign] = "Video>Cables" then true
else if [Campaign] = "Misc" then true
else if [Campaign] = "Serial ATA" then true
else if [Campaign] = "GPIB" then true
else if [Campaign] = "Audio>Cables" then true
else if [Campaign] = "USB>Misc" then true
else if [Campaign] = "Video>BNC" then true
else if [Campaign] = "Networking>Server Racks and Cabinets" then true
else if [Campaign] = "API Part Numbers 0-1500" then true
else if [Campaign] = "API Part Numbers 9000-10500" then true
else if [Campaign] = "API Part Numbers 6000-7500" then true
else if [Campaign] = "API Part Numbers 1500-3000" then true
else if [Campaign] = "API Part Numbers 3000-4500" then true
else if [Campaign] = "zBoost" then true
else if [Campaign] = "Liquidation Products" then true
else if [Campaign] = "Mobile" then true
else if [Campaign] = "HDMI Matrix Opt" then true
else if [Campaign] = "Server Racks" then true
else if [Campaign] = "Search Ads" then true
else if [Campaign] = "Yochi" then true
else if [Campaign] = "Local Targeting" then true
else if [Campaign] = "MOS Brand" then true
else if [Campaign] = "Campaign #2" then true
else if [Campaign] = "Campaign #5" then true
else if [Campaign] = "USB>Cables" then true
else if [Campaign] = "Video Splitter - OLD" then true
else if [Campaign] = "USB to Audio Adapter" then true
else if [Campaign] = "Other Products" then true
else if [Campaign] = "USB to Parallel Adapter - UK" then true
else if [Campaign] = "USB to Parallel Adapter - Germany" then true
else if [Campaign] = "USB to Parallel - Australia / NZ - OLD" then true
else if [Campaign] = "Docking Stations - Chinese" then true
else if [Campaign] = "Docking Stations - Dutch" then true
else if [Campaign] = "Docking Stations - Italian" then true
else if [Campaign] = "Docking Stations - French" then true
else if [Campaign] = "USB to Parallel Adapter - South Korea" then true
else if [Campaign] = "USB to Parallel Adapter - other English countries" then true
else if [Campaign] = "USB to Serial Adapter - Australia/NZ" then true
else if [Campaign] = "USB to Serial Adapter - Chinese Countries" then true
else if [Campaign] = "Networking" then true
else if [Campaign] = "iPod Accessories" then true
else if [Campaign] = "511" then true
else if [Campaign] = "512" then true
else if [Campaign] = "DVI>Splitters" then true
else if [Campaign] = "DVI>Switches" then true
else if [Campaign] = "Expresscards" then true
else if [Campaign] = "FireWire" then true
else if [Campaign] = "Video>Webcams & Mics" then true
else if [Campaign] = "Fiber Optics" then true
else if [Campaign] = "Competitors" then true
else if [Campaign] = "Clearance Store" then true
else if [Campaign] = "Networking>VPN Concentrators" then true
else if [Campaign] = "MFG Part Numbers" then true
else if [Campaign] = "July 2008 Optimized Products - Jimmy" then true
else if [Campaign] = "API Part Numbers 4500-6000" then true
else if [Campaign] = "Epiphan Products" then true
else if [Campaign] = "Inventory Optimization" then true
else if [Campaign] = "Sewell Dressups" then true
else if [Campaign] = "Kvaser" then true
else if [Campaign] = "YouTube Promoted Videos Campaign" then true
else if [Campaign] = "SW HV, Low CTR" then true
else if [Campaign] = "Rings: Ethan Dumont" then true
else if [Campaign] = "Branded" then true
else if [Campaign] = "Home Theater and TV Accessories" then true
else if [Campaign] = "Drew Opt" then true
else if [Campaign] = "Saffron" then true
else if [Campaign] = "Blyber Fronday 2014" then true
else if [Campaign] = "Oh, Canada" then true
else if [Campaign] = "Drift Search" then true
else if [Campaign] = "Black Friday" then true
else if [Campaign] = "Campaign #1" then true
else if [Campaign] = "Campaign #3" then true
else if [Campaign] = "FireWire>Cards" then true
else if [Campaign] = "FireWire>Extension Cable" then true
else if [Campaign] = "Campaign #35" then true
else if [Campaign] = "USB Passive Extension Cable" then true
else if [Campaign] = "Targus Universal Camera Bag" then true
else if [Campaign] = "USB to IDE Adapter" then true
else if [Campaign] = "USB to Parallel Adapter - France" then true
else if [Campaign] = "USB to Parallel Adapter - Scandinavia" then true
else if [Campaign] = "Docking Stations - Scandinavian" then true
else if [Campaign] = "USB to Serial Adapter - UK" then true
else if [Campaign] = "USB to Serial Adapter - Japan" then true
else if [Campaign] = "USB to Serial Adapter - South Korea" then true
else if [Campaign] = "Cat5e Cables" then true
else if [Campaign] = "External DVD/CD-RW" then true
else if [Campaign] = "DVI>Cables" then true
else if [Campaign] = "Cameron Postelwait" then true
else if [Campaign] = "Devin Collier" then true
else if [Campaign] = "Bluetooth" then true
else if [Campaign] = "Hard Drive>Enclosures" then true
else if [Campaign] = "HDMI>Converters" then true
else if [Campaign] = "Power" then true
else if [Campaign] = "PS/2" then true
else if [Campaign] = "Serial" then true
else if [Campaign] = "USB>Switches" then true
else if [Campaign] = "Storage" then true
else if [Campaign] = "Video Cards" then true
else if [Campaign] = "Video>ADC" then true
else if [Campaign] = "Wireless HDMI - Content" then true
else if [Campaign] = "Weekend Campaign" then true
else if [Campaign] = "Old Stuff" then true
else if [Campaign] = "Ethan Dumont" then true
else if [Campaign] = "Greg's New Stuff" then true
else if [Campaign] = "DSLR Accessories" then true
else if [Campaign] = "Computer Accessories" then true
else if [Campaign] = "Campaign #1" then true
else if [Campaign] = "ikiki Search Only Opt" then true
else false)